FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential automake pkg-config libtool gtk-doc-tools libglib2.0-dev libfreetype6-dev

COPY . /repo
WORKDIR /repo
RUN autoreconf -if
RUN ./configure
RUN make -j8
ENV LD_LIBRARY_PATH=/repo/chafa/.libs
